
-- Remove older duplicate so canonical custom slug can be inserted
DELETE FROM public.projects WHERE slug = 'rajapushpa-sierra';

INSERT INTO public.projects (slug, name, builder, location, city, configuration, bhk_list, property_type, price_range, min_price_inr, max_price_inr, status, possession, usp, description, hero_image, custom_page_path, canonical_url, seo_title, meta_description, featured)
VALUES
('tridasa-rise', 'Tridasa Rise', 'Tridasa Group', 'Nallagandla', 'Hyderabad', '3 & 4 BHK', ARRAY[3,4], 'Apartment', '₹2.5 Cr - ₹4.5 Cr', 25000000, 45000000, 'Under Construction', 'Dec 2027', 'Premium high-rise at Nallagandla with resort-style amenities', 'Premium 3 & 4 BHK luxury apartments at Nallagandla by Tridasa Group, designed for HITEC City professionals seeking elevated living with resort amenities.', '/placeholder.svg', '/projects/tridasa-rise', 'https://www.naani.in/projects/tridasa-rise', 'Tridasa Rise Nallagandla | 3 & 4 BHK Luxury Apartments', 'Tridasa Rise — premium 3 & 4 BHK apartments in Nallagandla, Hyderabad. RERA-approved high-rise with luxury amenities. Call +91 9705080909.', true),
('rajapushpa-sierra-tellapur-hyderabad', 'Rajapushpa Sierra', 'Rajapushpa Properties', 'Tellapur', 'Hyderabad', '3 & 4 BHK', ARRAY[3,4], 'Apartment', '₹2.8 Cr onwards', 28000000, 60000000, 'Under Construction', 'Dec 2028', '49-floor luxury high-rise above the city skyline', '49-floor premium high-rise apartments in Tellapur by Rajapushpa Properties. Sky-living, ultra-luxury amenities, ORR-facing residences.', '/placeholder.svg', '/projects/rajapushpa-sierra-tellapur-hyderabad', 'https://www.naani.in/projects/rajapushpa-sierra-tellapur-hyderabad', 'Rajapushpa Sierra Tellapur | 49-Floor Luxury Apartments', 'Rajapushpa Sierra — 49-storey luxury high-rise in Tellapur, Hyderabad. Premium 3 & 4 BHK with sky amenities. Call +91 9705080909.', true),
('team4-aria-miyapur-luxury-apartments-hyderabad', 'Team4 Aria', 'Team4 Group', 'Miyapur', 'Hyderabad', '2, 3 & 4 BHK', ARRAY[2,3,4], 'Apartment', '₹1.2 Cr onwards', 12000000, 30000000, 'Under Construction', 'Jun 2027', 'Modern luxury apartments in fast-growing Miyapur', 'Team4 Aria — luxury 2/3/4 BHK apartments at Miyapur with metro connectivity, premium clubhouse and modern architecture.', '/placeholder.svg', '/projects/team4-aria-miyapur-luxury-apartments-hyderabad', 'https://www.naani.in/projects/team4-aria-miyapur-luxury-apartments-hyderabad', 'Team4 Aria Miyapur | 2, 3 & 4 BHK Luxury Apartments', 'Team4 Aria — premium apartments in Miyapur, Hyderabad. Metro-connected luxury living. Call +91 9705080909.', true),
('sri-soho-interiors-designers-hyderabad', 'Sri Soho Interiors', 'Sri Soho', 'Hyderabad', 'Hyderabad', 'Interior Design', ARRAY[]::int[], 'Interior Design', 'Custom Quote', NULL, NULL, 'Available', 'On Demand', 'Premium interior design studio for Hyderabad homes', 'Sri Soho Interiors — bespoke interior design studio for luxury apartments and villas in Hyderabad.', '/placeholder.svg', '/projects/sri-soho-interiors-designers-hyderabad', 'https://www.naani.in/projects/sri-soho-interiors-designers-hyderabad', 'Sri Soho Interiors | Premium Interior Designers Hyderabad', 'Sri Soho Interiors — premium interior designers for luxury apartments & villas in Hyderabad. Custom designs. Call +91 9705080909.', true),
('aspire-spaces-a3-bachupally', 'Aspire Spaces A3', 'Aspire Spaces', 'Bachupally', 'Hyderabad', '2 & 3 BHK', ARRAY[2,3], 'Apartment', 'Click to Unlock', NULL, NULL, 'Under Construction', '2027', 'Smart-priced premium apartments in Bachupally', 'Aspire Spaces A3 — modern 2 & 3 BHK apartments in Bachupally with thoughtful amenities and excellent connectivity.', '/placeholder.svg', '/projects/aspire-spaces-a3-bachupally', 'https://www.naani.in/projects/aspire-spaces-a3-bachupally', 'Aspire Spaces A3 Bachupally | 2 & 3 BHK Apartments', 'Aspire Spaces A3 — premium 2 & 3 BHK apartments in Bachupally, Hyderabad. RERA approved. Call +91 9705080909.', true),
('man-airport-residency-4bhk-villas-near-me-tukkuguda-hyderabad', 'Man Airport Residency', 'Man Group', 'Tukkuguda', 'Hyderabad', '4 BHK Villas', ARRAY[4], 'Villa', '₹3.5 Cr onwards', 35000000, 55000000, 'Under Construction', '2027', 'Premium 4 BHK villas near Shamshabad Airport', 'Man Airport Residency — luxury 4 BHK villas in Tukkuguda, just minutes from Shamshabad International Airport.', '/placeholder.svg', '/projects/man-airport-residency-4bhk-villas-near-me-tukkuguda-hyderabad', 'https://www.naani.in/projects/man-airport-residency-4bhk-villas-near-me-tukkuguda-hyderabad', 'Man Airport Residency Tukkuguda | 4 BHK Luxury Villas', '4 BHK luxury villas at Tukkuguda near Shamshabad Airport. Gated community with premium amenities. Call +91 9705080909.', true),
('brigade-gateway-neopolis-kokapet-hyderabad', 'Brigade Gateway Neopolis', 'Brigade Group', 'Kokapet', 'Hyderabad', '3 & 4 BHK', ARRAY[3,4], 'Apartment', '₹3.2 Cr onwards', 32000000, 70000000, 'Under Construction', '2028', 'Brigade luxury living in Neopolis Kokapet', 'Brigade Gateway Neopolis — landmark luxury high-rise in Kokapet by Brigade Group, designed for HNIs and global Hyderabad.', '/placeholder.svg', '/projects/brigade-gateway-neopolis-kokapet-hyderabad', 'https://www.naani.in/projects/brigade-gateway-neopolis-kokapet-hyderabad', 'Brigade Gateway Neopolis Kokapet | Luxury Apartments', 'Brigade Gateway Neopolis — luxury 3 & 4 BHK apartments in Kokapet by Brigade Group. Call +91 9705080909.', true),
('prestige-golden-grove-hyderabad', 'Prestige Golden Grove', 'Prestige Group', 'Bachupally', 'Hyderabad', '2, 3 & 4 BHK', ARRAY[2,3,4], 'Apartment', '₹1.5 Cr onwards', 15000000, 40000000, 'Pre-Launch', '2028', 'Prestige Group luxury apartments in Hyderabad', 'Prestige Golden Grove — premium gated community by Prestige Group with world-class amenities and elegant design.', '/placeholder.svg', '/projects/prestige-golden-grove-hyderabad', 'https://www.naani.in/projects/prestige-golden-grove-hyderabad', 'Prestige Golden Grove Hyderabad | Luxury Apartments', 'Prestige Golden Grove — premium 2/3/4 BHK apartments in Hyderabad by Prestige Group. Call +91 9705080909.', true),
('jaycon-gateway-tirupati', 'Jaycon Gateway', 'Jaycon Builders', 'Tirupati', 'Tirupati', '2 & 3 BHK', ARRAY[2,3], 'Apartment', '₹65 L onwards', 6500000, 15000000, 'Under Construction', '2027', 'Premium gated apartments in Tirupati', 'Jaycon Gateway — premium 2 & 3 BHK apartments in Tirupati offering modern living near temple town infrastructure.', '/placeholder.svg', '/projects/jaycon-gateway-tirupati', 'https://www.naani.in/projects/jaycon-gateway-tirupati', 'Jaycon Gateway Tirupati | 2 & 3 BHK Apartments', 'Jaycon Gateway — premium 2 & 3 BHK apartments in Tirupati with modern amenities. Call +91 9705080909.', true)
ON CONFLICT (slug) DO UPDATE SET
  custom_page_path = EXCLUDED.custom_page_path,
  canonical_url = EXCLUDED.canonical_url,
  featured = true,
  hero_image = COALESCE(public.projects.hero_image, EXCLUDED.hero_image);
